var KLDMaster = [
{Name:"Cataclysmic Gearhulk", Cost:"3WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"1", Image:"/Images/KldMaster/CataclysmicGearhulk.jpg", },
{Name:"Torrential Gearhulk", Cost:"4UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"2", Image:"/Images/KldMaster/TorrentialGearhulk.jpg", },
{Name:"Noxious Gearhulk", Cost:"4BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"3", Image:"/Images/KldMaster/NoxiousGearhulk.jpg", },
{Name:"Combustible Gearhulk", Cost:"4RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"4", Image:"/Images/KldMaster/CombustibleGearhulk.jpg", },
{Name:"Verdurous Gearhulk", Cost:"3GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"5", Image:"/Images/KldMaster/VerdurousGearhulk.jpg", },
{Name:"Sword of Light and Shadow", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"6", Image:"/Images/KldMaster/SwordofLightandShadow.jpg", },
{Name:"Sword of Fire and Ice", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"7", Image:"/Images/KldMaster/SwordofFireandIce.jpg", },
{Name:"Sword of Feast and Famine", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"8", Image:"/Images/KldMaster/SwordofFeastandFamine.jpg", },
{Name:"Steel Overseer", Cost:"2", Color:["C"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"9", Image:"/Images/KldMaster/SteelOverseer.jpg", },
{Name:"Static Orb", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"10", Image:"/Images/KldMaster/StaticOrb.jpg", },
{Name:"Solemn Simulacrum", Cost:"4", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"11", Image:"/Images/KldMaster/SolemnSimulacrum.jpg", },
{Name:"Sol Ring", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"12", Image:"/Images/KldMaster/SolRing.jpg", },
{Name:"Sculpting Steel", Cost:"1", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"13", Image:"/Images/KldMaster/SculptingSteel.jpg", },
{Name:"Mox Opal", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"14", Image:"/Images/KldMaster/MoxOpal.jpg", },
{Name:"Painter's Servant", Cost:"0", Color:["C"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"15", Image:"/Images/KldMaster/PaintersServant.jpg", },
{Name:"Rings of Brighthearth", Cost:"2", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"16", Image:"/Images/KldMaster/RingsofBrighthearth.jpg", },
{Name:"Scroll Rack", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"17", Image:"/Images/KldMaster/ScrollRack.jpg", },
{Name:"Lightning Greaves", Cost:"2", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"18", Image:"/Images/KldMaster/LightningGreaves.jpg", },
{Name:"Lotus Petal", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"19", Image:"/Images/KldMaster/LotusPetal.jpg", },
{Name:"Mana Vault", Cost:"1", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"20", Image:"/Images/KldMaster/ManaVault.jpg", },
{Name:"Mind's Eye", Cost:"5", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"21", Image:"/Images/KldMaster/MindsEye.jpg", },
{Name:"Crucible of Worlds", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"22", Image:"/Images/KldMaster/CrucibleofWorlds.jpg", },
{Name:"Cloudstone Curio", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"23", Image:"/Images/KldMaster/CloudstoneCurio.jpg", },
{Name:"Chrome Mox", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"24", Image:"/Images/KldMaster/ChromeMox.jpg", },
{Name:"Chromatic Lantern", Cost:"3", Color:["C"], Rarity:"M", Type:["A","A"], Rating:"9", Sort:"1", Set:"KLD", Number:"25", Image:"/Images/KldMaster/ChromaticLantern.jpg", },
{Name:"Champion's Helm", Cost:"3", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"26", Image:"/Images/KldMaster/ChampionsHelm.jpg", },
{Name:"Aether Vial", Cost:"1", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"27", Image:"/Images/KldMaster/AetherVial.jpg", },
{Name:"Mana Crypt", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"28", Image:"/Images/KldMaster/ManaCrypt.jpg", },
{Name:"Gauntlet of Power", Cost:"5", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"29", Image:"/Images/KldMaster/GauntletofPower.jpg", },
{Name:"Hangarback Walker", Cost:"0", Color:["C"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"30", Image:"/Images/KldMaster/HangarbackWalker.jpg", }
];